### ISSUE TITLE
h264_vaapi

### ISSUE THREAD

**Issue by fferroni** [berndpfrommer/ffmpeg_image_transport#13]
Hi,
Have you ever tried using `h264_vaapi` as an encoder? It doesn't seem to accept `preset` options.
https://trac.ffmpeg.org/wiki/Hardware/VAAPI#Mappingoptionsfromlibx264

**Comment by berndpfrommer** [comment]
I have never tried vaapi. What error are you getting? From looking at the code, it should continue even if setting the preset returns an error. What's not working?

**Comment by fferroni** [comment]
It complains that it does not accept `preset` as a parameter.

**Comment by berndpfrommer** [comment]
The encoding looks quite different from what worked for nvenc. Here is an example of vaapi encoding:
https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/vaapi_encode.c

**Comment by berndpfrommer** [comment]
I added support for VAAPI. Tested on AMD laptop.
